# GitHub CI build pipeline
name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install coverage
          if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Unit Tests and generate coverage report
        run: |
          cd src
          python -m unittest -v
          coverage run -m unittest
          coverage report
          coverage html
      - name: Archive code coverage html report
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: code-coverage-report
          path: src/htmlcov
      - name: Run package creation
        run: |
          cd src
          python -m pip install --user --upgrade build
          python -m build
      - name: Archive package
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: awesome-calculator
          path: src/dist

  install-wheel:
    needs: build  # Ensures this job only runs after the build job completes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download the .whl artifact
        uses: actions/download-artifact@v3
        with:
          name: awesome-calculator
          path: ./dist  # Downloads the artifact to the 'dist' folder

      - name: List files in dist after download
        run: ls -al /home/runner/work/awesomecalculator/awesomecalculator/dist  # Debugging step to list files

      - name: Install the wheel file
        run: |
          cd /home/runner/work/awesomecalculator/awesomecalculator/dist
          pip install awesome_calculator-*.whl  # Install the wheel file
